2024-12-17 18:48:38,594 - asyncio - DEBUG - Using proactor: IocpProactor
2024-12-17 18:48:38,598 - root - INFO - Searching for GoPro cameras...
2024-12-17 18:48:38,778 - root - INFO - Discovered GoPro: C3461326143885._gopro-web._tcp.local. at 172.28.185.51
2024-12-17 18:48:38,781 - root - INFO - Discovered GoPro: C3461350386740._gopro-web._tcp.local. at 172.27.140.51
2024-12-17 18:48:43,605 - root - INFO - Found the following GoPro devices:
2024-12-17 18:48:43,605 - root - INFO - Name: C3461326143885._gopro-web._tcp.local., IP: 172.28.185.51
2024-12-17 18:48:43,607 - root - INFO - Name: C3461350386740._gopro-web._tcp.local., IP: 172.27.140.51
2024-12-17 18:48:43,609 - root - INFO - Cache updated successfully with newly discovered devices.
2024-12-17 18:48:43,609 - root - INFO - Resetting and enabling USB control on all cameras...
2024-12-17 18:48:43,610 - root - INFO - Resetting USB control on camera 172.28.185.51.
2024-12-17 18:48:43,611 - root - INFO - Resetting USB control on camera 172.27.140.51.
2024-12-17 18:48:43,621 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 18:48:43,622 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 18:48:43,680 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 500 3
2024-12-17 18:48:43,681 - root - ERROR - Failed to disable USB control on camera 172.27.140.51. Status Code: 500. Response: {}

2024-12-17 18:48:43,686 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 200 3
2024-12-17 18:48:43,687 - root - INFO - USB control disabled on camera 172.28.185.51.
2024-12-17 18:48:45,684 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 18:48:45,689 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 18:48:45,736 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 500 3
2024-12-17 18:48:45,737 - root - ERROR - Failed to enable USB control on camera 172.27.140.51. Status Code: 500. Response: {}

2024-12-17 18:48:45,765 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 18:48:45,766 - root - INFO - USB control enabled on camera 172.28.185.51.
2024-12-17 18:48:45,767 - root - INFO - Synchronizing time on all cameras...
2024-12-17 18:48:45,768 - root - ERROR - Failed to sync time: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
2024-12-17 18:48:45,769 - root - ERROR - An error occurred: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
