2024-12-17 18:50:36,375 - asyncio - DEBUG - Using proactor: IocpProactor
2024-12-17 18:50:36,383 - root - INFO - Searching for GoPro cameras...
2024-12-17 18:50:36,597 - root - INFO - Discovered GoPro: C3461326143885._gopro-web._tcp.local. at 172.28.185.51
2024-12-17 18:50:36,614 - root - INFO - Discovered GoPro: C3461350386740._gopro-web._tcp.local. at 172.27.140.51
2024-12-17 18:50:41,408 - root - INFO - Found the following GoPro devices:
2024-12-17 18:50:41,408 - root - INFO - Name: C3461326143885._gopro-web._tcp.local., IP: 172.28.185.51
2024-12-17 18:50:41,409 - root - INFO - Name: C3461350386740._gopro-web._tcp.local., IP: 172.27.140.51
2024-12-17 18:50:41,410 - root - INFO - Cache updated successfully with newly discovered devices.
2024-12-17 18:50:41,410 - root - INFO - Resetting and enabling USB control on all cameras...
2024-12-17 18:50:41,411 - root - INFO - Resetting USB control on camera 172.28.185.51.
2024-12-17 18:50:41,412 - root - INFO - Resetting USB control on camera 172.27.140.51.
2024-12-17 18:50:41,419 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 18:50:41,420 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 18:50:41,510 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 200 3
2024-12-17 18:50:41,511 - root - INFO - USB control disabled on camera 172.28.185.51.
2024-12-17 18:50:41,534 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 500 3
2024-12-17 18:50:41,535 - root - ERROR - Failed to disable USB control on camera 172.27.140.51. Status Code: 500. Response: {}

2024-12-17 18:50:43,513 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 18:50:43,538 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 18:50:43,603 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 18:50:43,604 - root - INFO - USB control enabled on camera 172.28.185.51.
2024-12-17 18:50:43,620 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 18:50:43,620 - root - INFO - USB control enabled on camera 172.27.140.51.
2024-12-17 18:50:43,621 - root - INFO - Synchronizing time on all cameras...
2024-12-17 18:50:43,623 - root - ERROR - Failed to sync time: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
2024-12-17 18:50:43,623 - root - ERROR - An error occurred: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
