2024-12-17 19:05:10,043 - asyncio - DEBUG - Using proactor: IocpProactor
2024-12-17 19:05:10,047 - root - INFO - Searching for GoPro cameras...
2024-12-17 19:05:10,194 - root - INFO - Discovered GoPro: C3461350386740._gopro-web._tcp.local. at 172.27.140.51
2024-12-17 19:05:10,270 - root - INFO - Discovered GoPro: C3461326143885._gopro-web._tcp.local. at 172.28.185.51
2024-12-17 19:05:15,052 - root - INFO - Found the following GoPro devices:
2024-12-17 19:05:15,052 - root - INFO - Name: C3461350386740._gopro-web._tcp.local., IP: 172.27.140.51
2024-12-17 19:05:15,060 - root - INFO - Name: C3461326143885._gopro-web._tcp.local., IP: 172.28.185.51
2024-12-17 19:05:15,062 - root - INFO - Cache updated successfully with newly discovered devices.
2024-12-17 19:05:15,063 - root - INFO - Resetting and enabling USB control on all cameras...
2024-12-17 19:05:15,064 - root - INFO - Resetting USB control on camera 172.27.140.51.
2024-12-17 19:05:15,066 - root - INFO - Resetting USB control on camera 172.28.185.51.
2024-12-17 19:05:15,078 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 19:05:15,080 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 19:05:15,164 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 500 3
2024-12-17 19:05:15,165 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=0 HTTP/11" 500 3
2024-12-17 19:05:15,165 - root - ERROR - Failed to disable USB control on camera 172.28.185.51. Status Code: 500. Response: {}

2024-12-17 19:05:15,166 - root - ERROR - Failed to disable USB control on camera 172.27.140.51. Status Code: 500. Response: {}

2024-12-17 19:05:17,167 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.28.185.51:8080
2024-12-17 19:05:17,169 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 172.27.140.51:8080
2024-12-17 19:05:17,250 - urllib3.connectionpool - DEBUG - http://172.28.185.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 19:05:17,251 - root - INFO - USB control enabled on camera 172.28.185.51.
2024-12-17 19:05:17,251 - urllib3.connectionpool - DEBUG - http://172.27.140.51:8080 "GET /gopro/camera/control/wired_usb?p=1 HTTP/11" 200 3
2024-12-17 19:05:17,251 - root - INFO - USB control enabled on camera 172.27.140.51.
2024-12-17 19:05:17,252 - root - INFO - Synchronizing time on all cameras...
2024-12-17 19:05:17,254 - root - ERROR - Failed to sync time: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
2024-12-17 19:05:17,254 - root - ERROR - An error occurred: cannot import name 'sync_time' from 'date_time_sync' (c:\!AndriiShramko\inventions\SDKGOPROShramko\GoProControl\api\v2\v39\date_time_sync.py)
